-- *****************************************************************
-- PORTAL DO CENTRO ACADÊMICO (CA) - SCRIPT FINAL DE ESTRUTURA
-- Arquitetura: PostgreSQL (Supabase) + RLS (Row Level Security)
-- Este script cria todas as tabelas e políticas de segurança.
-- *****************************************************************

-- 1. CRIAÇÃO DAS TABELAS
-------------------------------------------------------------------

-- 1.1 Tabela de NOTÍCIAS (CRUD de conteúdo público)
CREATE TABLE public.noticias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  titulo TEXT NOT NULL,
  data DATE,
  resumo TEXT
);

-- 1.2 Tabela de EVENTOS (CRUD de conteúdo para o calendário)
CREATE TABLE public.eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  titulo TEXT NOT NULL,
  data DATE,
  local TEXT
);

-- 1.3 Tabela de DOCUMENTOS (Para gerenciar uploads de arquivos)
CREATE TABLE public.documentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  titulo TEXT NOT NULL,
  descricao TEXT,
  caminho_storage TEXT NOT NULL, -- Caminho interno no Storage
  url_publica TEXT NOT NULL     -- Link de download público
);

-- 1.4 Tabela de DENÚNCIAS (Canal anônimo de contato)
CREATE TABLE public.denuncias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  tipo TEXT,
  descricao TEXT
);

-- 2. HABILITAR SEGURANÇA (RLS)
-------------------------------------------------------------------

-- Deve ser habilitado em todas as tabelas de dados
ALTER TABLE public.noticias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eventos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.denuncias ENABLE ROW LEVEL SECURITY;

-- 3. STORAGE DE ARQUIVOS (Para Documentos)
-------------------------------------------------------------------

-- Cria o "Balde" (Bucket) no Storage
INSERT INTO storage.buckets (id, name, public)
VALUES ('documentos', 'documentos', true)
ON CONFLICT (id) DO NOTHING; -- Evita erro se o balde já existir

-- 4. POLÍTICAS DE SEGURANÇA (RLS) DO BANCO DE DADOS
-------------------------------------------------------------------

-- Nossos dois perfis: 'anon' (público/visível) e 'authenticated' (admin)

-- 4.1. POLÍTICAS DE NOTÍCIAS
CREATE POLICY "noticias_select_public" ON public.noticias FOR SELECT USING (true);
CREATE POLICY "noticias_crud_admin" ON public.noticias FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- 4.2. POLÍTICAS DE EVENTOS
CREATE POLICY "eventos_select_public" ON public.eventos FOR SELECT USING (true);
CREATE POLICY "eventos_crud_admin" ON public.eventos FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- 4.3. POLÍTICAS DE DOCUMENTOS (Somente a tabela de dados)
CREATE POLICY "documentos_select_public" ON public.documentos FOR SELECT USING (true);
CREATE POLICY "documentos_crud_admin" ON public.documentos FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- 4.4. POLÍTICAS DE DENÚNCIAS
CREATE POLICY "denuncias_insert_anon" ON public.denuncias FOR INSERT WITH CHECK (true); -- Público pode enviar
CREATE POLICY "denuncias_select_admin" ON public.denuncias FOR SELECT USING (auth.role() = 'authenticated'); -- Admin pode ler
CREATE POLICY "denuncias_delete_admin" ON public.denuncias FOR DELETE USING (auth.role() = 'authenticated'); -- Admin pode apagar

-- 5. POLÍTICAS DE SEGURANÇA DO STORAGE (Arquivos de Documentos)
-------------------------------------------------------------------

-- 5.1 Permite que QUALQUER UM (público) LEIA/BAIXE os arquivos do 'documentos'
CREATE POLICY "storage_docs_select_public"
ON storage.objects FOR SELECT
USING (bucket_id = 'documentos');

-- 5.2 Permite que usuários LOGADOS (admins) façam UPLOAD no 'documentos'
CREATE POLICY "storage_docs_insert_admin"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'documentos' AND auth.role() = 'authenticated');

-- 5.3 Permite que usuários LOGADOS (admins) DELETEM arquivos do 'documentos'
CREATE POLICY "storage_docs_delete_admin"
ON storage.objects FOR DELETE
USING (bucket_id = 'documentos' AND auth.role() = 'authenticated');

-- FIM DO SCRIPT